# Generated by Django 3.2 on 2022-06-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_income',
            field=models.IntegerField(default='', max_length=50),
        ),
    ]
