# Generated by Django 3.2 on 2022-06-09 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_career',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_tel',
        ),
    ]
