# Generated by Django 3.2 on 2022-06-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20220609_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='user_career',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.EmailField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='user_tel',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='department',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
