# Generated by Django 3.2 on 2022-06-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_user_user_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_income',
            field=models.IntegerField(default='1000', max_length=50),
        ),
    ]
