# Generated by Django 3.2 on 2022-06-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_alter_user_user_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_income',
            field=models.IntegerField(),
        ),
    ]
