# Generated by Django 3.2 on 2022-06-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20220609_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_income',
            field=models.IntegerField(default=1000),
        ),
    ]
